### PR TITLE
Handle retaining explicit formatting characters + other fixes

### LINKED ISSUE #89: Handle removed explicit formatting characters
[X9](https://www.unicode.org/reports/tr9/#X9) asks us to remove all explicit formatting characters from the string.

We do not do this. The spec has provisions for implementations that wish to retain these characters, namely the section [_Retaining BNs and Explicit Formatting Characters_](https://www.unicode.org/reports/tr9/#Retaining_Explicit_Formatting_Characters). It contains a whole bunch of stuff that we should do instead, that we're also not doing.

We should fix that :smile:

### LINKED ISSUE #90: Analysis of failing character tests (after #85)
This is where I'm tracking all of the failures left in the character tests after #85 and #91. This is not checking the 314 failures (250 after #87) for the basic tests.

I'm categorizing them by their section in BidiConformanceTest.txt, and filling in issue numbers as necessary. Investigations on the ??s would be appreciated! 

Explicit directional overrides applied to paired brackets (https://github.com/servo/unicode-bidi/issues/89)
<details><summary>8 tests</summary>

```
202A 05D0 0028 05D1 202C 202D 0029;2;1;x 3 3 3 x x 2;3 2 1 6
202A 05D0 0028 05D1 202C 202D 0029 202C;2;1;x 3 3 3 x x 2 x;3 2 1 6
202B 0061 0028 0062 202C 202E 0029;2;0;x 2 2 2 x x 1;6 1 2 3
202B 0061 0028 0062 202C 202E 0029 202C;2;0;x 2 2 2 x x 1 x;6 1 2 3
202D 0028 202C 202A 05D0 0029 05D1;2;1;x 2 x x 3 3 3;1 6 5 4
202D 0028 202C 202A 05D0 0029 05D1 202C;2;1;x 2 x x 3 3 3 x;1 6 5 4
202E 0028 202C 202B 0061 0029 0062;2;0;x 1 x x 2 2 2;4 5 6 1
202E 0028 202C 202B 0061 0029 0062 202C;2;0;x 1 x x 2 2 2 x;4 5 6 1
```
</details>

Nonspacing marks applied to paired brackets. These cases exercise the ignoring of bc=BN characters (#89, probably)

<details><summary>4 tests</summary>

```
0041 200F 005B 05D0 005D 200D 20D6;0;0;0 1 1 1 1 x 1;0 6 4 3 2 1
0041 200F 005B 200D 20D6 05D0 005D;0;0;0 1 1 x 1 1 1;0 6 5 4 2 1
0041 200F 005B 200D 20D6 05D0 005D 200D 20D6;0;0;0 1 1 x 1 1 1 x 1;0 8 6 5 4 2 1
0041 200F 005B 200D 200B 20D6 05D0 005D 200B 200D 20D6;0;0;0 1 1 x x 1 1 1 x x 1;0 10 7 6 5 2 1
```
</details>

Sequences containing directional formatting characters (https://github.com/servo/unicode-bidi/issues/89)

<details><summary>6 tests</summary>

```
0061 202D 202C 0020 0031 0020 0032 002D 0033;1;1;2 x x 2 2 2 2 2 2;0 3 4 5 6 7 8
0061 202E 202C 0020 0031 0020 0032 002D 0033;1;1;2 x x 2 2 2 2 2 2;0 3 4 5 6 7 8
0627 202A 202C 0020 0031 002D 0032;0;0;1 x x 1 2 1 2;6 5 4 3 0
0627 202B 202C 0020 0031 002D 0032;0;0;1 x x 1 2 1 2;6 5 4 3 0
05D0 202A 202A 202C 202C 0020 0031 0020 0032;0;0;1 x x x x 1 2 1 2;8 7 6 5 0
0061 202B 202B 202C 202C 0020 0031 0020 0032;1;1;2 x x x x 2 2 2 2;0 5 6 7 8
```
</details>

Combinations of paired brackets, numbers, and directional formatting characters  (probably involves some of https://github.com/servo/unicode-bidi/issues/89)

<details><summary>11 tests</summary>

```
2066 0029 0029 0661 0028 0627 0029;1;1;1 2 2 4 3 3 3;1 2 6 5 4 3 0
2066 0029 0029 0661 0028 0662 0029;1;1;1 2 2 4 3 4 3;1 2 6 5 4 3 0
2066 0029 2066 0661 0028 05D0 0029;1;1;1 2 2 6 5 5 5;1 2 6 5 4 3 0
0061 0028 0062 005B 0063 2068 05D0 2069 0064 005D 0065 0029 0066;1;1;2 2 2 2 2 2 3 2 2 2 2 2 2;0 1 2 3 4 5 6 7 8 9 10 11 12
05D0 0028 05D1 005B 05D2 2068 0061 2069 05D3 005D 05D4 0029 05D5;0;0;1 1 1 1 1 1 2 1 1 1 1 1 1;12 11 10 9 8 7 6 5 4 3 2 1 0
0061 0028 0062 2067 05D0 005B 05D1 2066 0063 05D3 2069 0065 005D 0066 2069 05D4 0029 05D5;0;0;0 0 0 0 1 1 1 1 2 3 1 2 1 2 0 1 0 1;0 1 2 3 13 12 11 10 8 9 7 6 5 4 14 15 16 17
0061 0028 0062 2067 05D0 005B 05D1 2066 0063 007B 0064 202B 007D 0020 007B 202C 05D2 007D 05D3 2069 0065 005D 0066 2069 05D4 0029 05D5;0;0;0 0 0 0 1 1 1 1 2 2 2 x 3 3 3 x 3 3 3 1 2 1 2 0 1 0 1;0 1 2 3 22 21 20 19 8 9 10 18 17 16 14 13 12 7 6 5 4 23 24 25 26
0061 0028 0062 2067 05D0 005B 05D1 2066 0063 007B 0064 202B 007D 0020 007B 202C 05D2 007D 05D3 2069 0065 005D 0066 2069 05D4 0029 05D5;1;1;2 1 2 1 3 3 3 3 4 4 4 x 5 5 5 x 5 5 5 3 4 3 4 1 1 1 1;26 25 24 23 22 21 20 19 8 9 10 18 17 16 14 13 12 7 6 5 4 3 2 1 0
05D0 0028 05D1 2066 0061 005B 0062 2067 05D2 0064 2069 05D4 005D 05D5 2069 0065 0029 0066;1;1;1 1 1 1 2 2 2 2 3 4 2 3 2 3 1 2 1 2;17 16 15 14 4 5 6 7 9 8 10 11 12 13 3 2 1 0
05D0 0028 05D1 2066 0061 005B 0062 2067 05D2 007B 05D3 202A 007D 0020 007B 202C 0063 007D 0064 2069 05D4 005D 05D5 2069 0065 0029 0066;0;0;1 0 1 0 2 2 2 2 3 3 3 x 4 4 4 x 4 4 4 2 3 2 3 0 0 0 0;0 1 2 3 4 5 6 7 12 13 14 16 17 18 10 9 8 19 20 21 22 23 24 25 26
05D0 0028 05D1 2066 0061 005B 0062 2067 05D2 007B 05D3 202A 007D 0020 007B 202C 0063 007D 0064 2069 05D4 005D 05D5 2069 0065 0029 0066;1;1;1 1 1 1 2 2 2 2 3 3 3 x 4 4 4 x 4 4 4 2 3 2 3 1 2 1 2;26 25 24 23 4 5 6 7 12 13 14 16 17 18 10 9 8 19 20 21 22 3 2 1 0
```
</details>

### PR DESCRIPTION
**Pull request by Manishearth**
Built on top of https://github.com/servo/unicode-bidi/pull/91. PR starts at "Add all fixups for retaining explicits".

Fixes #89 by doing the implementation hacks specified in section 5.2 [Retaining BNs and Explicit Formatting Characters](https://www.unicode.org/reports/tr9/#Retaining_Explicit_Formatting_Characters).

This fixes all of the character tests! (fixes #90). <s>We still have to fix some of the "basic" tests, which are unfortunately not as nicely labeled as the character tests.</s> This also fixes the basic tests (fixes https://github.com/servo/unicode-bidi/issues/8 )

This got mixed in with a bunch of other fixes since a lot of the code is nearby, a bunch of them fix things from N0. The main Big Fix in here besides the one around retaining explicit formatting is that the code now _always_ handles lookahead/lookbehind by iterating within the run sequence only.

All in all, this PR contains:
 - Fixes for [Retaining BNs and Explicit Formatting Characters](https://www.unicode.org/reports/tr9/#Retaining_Explicit_Formatting_Characters) (#89)
 - A fix for a spec bug in BD16
 - A typo/indexing fix from my work in #85 (oops)
 - A sequence of changes so that all lookahead/lookbehind works within the run sequence only.
 - A bunch of rule ordering fixes in the W rules (#8)

### CODE REVIEW

**Comment by Manishearth** [comment]
We also probably should fuzz this crate to catch panics, and maybe also fuzz it against the reference implementation once _all_ tests pass.

**Review by sffc — COMMENTED** [review]
seems plausible; what type of review are you looking for?

**Comment by Manishearth** [comment]
@sffc I'm hoping @eggrobin can do spec review, and you can do general Rusty code review as well as "is this the best way to implement this step" review.

FWIW If you review everything here including the first two commits I don't need to get review on https://github.com/servo/unicode-bidi/pull/91.

File: src/explicit.rs [hunk 1]
```diff
@@ -47,13 +47,17 @@ pub fn compute(
             RLE | LRE | RLO | LRO | RLI | LRI | FSI => {
                 let last_level = stack.last().level;
 
+                // <https://www.unicode.org/reports/tr9/#Retaining_Explicit_Formatting_Characters>
+                levels[i] = last_level;
```
Comment (sffc) [inline src/explicit.rs:51]: I'm not super happy that all this code uses `[]` but you have another issue to follow up on that (fuzzing this crate to make sure it doesn't panic).

File: src/implicit.rs [hunk 2]
```diff
@@ -255,30 +310,40 @@ pub fn resolve_neutral<D: BidiDataSource>(
...
             for class in &mut processing_classes[pair.end..pair.end + end_len_utf8] {
                 *class = class_to_set;
             }
+            // <https://www.unicode.org/reports/tr9/#Retaining_Explicit_Formatting_Characters>
+            for idx in sequence.iter_backwards_from(pair.start, pair.start_run) {
+                let class = &mut processing_classes[idx];
+                if *class != BN {
+                    break;
+                }
+                *class = class_to_set;
```
Comment (sffc) [inline src/implicit.rs:326]: You're only setting one element; is this intentional, or do you need to set multiple elements? Is `processing_classes` in UTF-8 or UTF-32 indices?

**Review by sffc — COMMENTED** [review]
My reaction is that iter_forwards_from and iter_backwards_from seem to be good abstractions, but they still give you UTF-8 indices, yes? So if you want to "flip" a whole code point from one level or property to another, you need to overwrite all the bytes for that code point, right?

File: src/explicit.rs (hunk 1 above)
Comment (Manishearth) [reply src/explicit.rs:51]: Yeah the whole crate does this

File: src/implicit.rs (hunk 2 above)
Comment (Manishearth) [reply src/implicit.rs:326]: The loop makes this unnecessary; we are maintaining the property of every byte having its classes set so we don't have to worry about this. The existing code does this in many spots. I do want to clean this up by aggressively commenting or by building better abstractions. (Or potentially storing `Option<BidiClass>` or something)

Everything is in UTF-8 indices.

**Comment by Manishearth** [comment]
And all tests pass, now. Bonus fix for https://github.com/servo/unicode-bidi/issues/8

**Comment by Manishearth** [comment]
kick CI

File: src/explicit.rs [hunk 3]
```diff
@@ -132,22 +143,27 @@ pub fn compute(
...
             // <http://www.unicode.org/reports/tr9/#X6>
             _ => {
                 let last = stack.last();
                 levels[i] = last.level;
-                match last.status {
-                    OverrideStatus::RTL => processing_classes[i] = R,
-                    OverrideStatus::LTR => processing_classes[i] = L,
-                    _ => {}
+                // This condition is not in the spec, but I am pretty sure that is a spec bug
+                // https://github.com/unicode-org/properties/issues/71
```
Comment (eggrobin) [inline src/explicit.rs:160]: That is a reference to a private repository (and it has been deduplicated there).

Link to your proposal instead?

File: src/implicit.rs [hunk 4]
```diff
@@ -27,118 +26,200 @@ pub fn resolve_weak(
...
+                    if let Some(ch) = text.get(i..).and_then(|s| s.chars().next()) {
+                        let mut next_class = sequence
+                            .iter_forwards_from(i + ch.len_utf8(), run_index)
+                            .map(|j| processing_classes[j])
+                            // <https://www.unicode.org/reports/tr9/#Retaining_Explicit_Formatting_Characters>
+                            .find(not_removed_by_x9)
+                            .unwrap_or(sequence.eos);
+                        if next_class == EN && last_strong_is_al {
+                            // Apply W2 to next_class. We know that last_strong_is_al.
+                            // Has no chance of changing on this character so we can still presume its value.
```
Comment (eggrobin) [inline src/implicit.rs:132]: _presume_ feels like the wrong verb here.
We can preserve/reuse/retain its value? Or just we do not need to update it?

File: src/implicit.rs [hunk 5]
```diff
@@ -27,118 +26,200 @@ pub fn resolve_weak(
...
+    // Note: The spec treats these steps as individual passes that are applied one after the other
+    // on the entire IsolatingRunSequence at once. We instead collapse it into a single iteration,
+    // which is straightforward for rules that are based on the state of the current character, but not
+    // for rules that care about surrounding characters. To deal with them, we retain additional state
+    // about previous character classes that may have since been changed by later rules.
+
+    // The previous class for the purposes of rule W4/W6, not tracking changes made after or during W4.
+    let mut prev_w46_class = sequence.sos;
+    // The previous class for the purposes of rule W5.
+    let mut prev_w5_class = sequence.sos;
```
Comment (eggrobin) [inline src/implicit.rs:38]: But also for the purposes of one chunk of rule W6.

Instead of naming them as the class _for_ a rule, I would prefer if they were named as the class before (or, if you prefer, after) a rule, thus `previous_class_before_w5` or `previous_class_pre_w5` or `previous_class_after_w4` or `previous_class_post_w4`, likewise for the others.
(Also, in this context `prev` confused me somewhat because I was thinking it might mean `pre`, which is how I was thinking of these classes; that abbreviation may be OK if we have a `before`/`pre`/`after`/`post` in the identifier as well.)

File: src/implicit.rs [hunk 6]
```diff
@@ -27,118 +26,200 @@ pub fn resolve_weak(
...
+                                let class = &mut processing_classes[idx];
+                                if *class != BN {
+                                    break;
+                                }
+                                *class = ON;
+                            }
+                        }
+                    } else {
+                        // We're in the middle of a character, copy over work done for previous bytes
+                        // since it's going to be the same answer/
```
Comment (eggrobin) [inline src/implicit.rs:168]: Interesting choice of final punctuation/

**Review by eggrobin — APPROVED** [review]
