### PR TITLE
Fix char boundary bug

### LINKED ISSUE #138: `visual_range` can return invalid ranges leading to indexing panic
When using the `visual_runs` function on text containing LRE and PDF chars, the returned ranges may not match up with char boundaries.

```rust
fn main() {
    // U+202A = Left-to-Right Embedding (LRE)
    // U+202C = Pop Directional Formatting (PDF)
    //                |---------------|
    let s = "\u{202a}A\u{202c}\u{202a}A\u{202c}";
    let range = 4..11;
    assert!(s.get(range.clone()).is_some());

    let bidi = unicode_bidi::BidiInfo::new(s, None);
    let (_, runs) = bidi.visual_runs(&bidi.paragraphs[0], range);

    for run in runs {
        let _ = &s[run];
    }
}
```
```
thread 'main' panicked at src/main.rs:11:19:
byte index 5 is not a char boundary; it is inside '\u{202c}' (bytes 4..7) of `‪A‬‪A‬`
```

Perhaps it is strange to start a line at a PDF char, but either way I think it should not yield invalid ranges.

### PR DESCRIPTION
**Pull request by A-Walrus**
Fixes #138 

Set all bytes of char to prev_level.

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]
This looks good, but could you add some tests?

File: src/lib.rs [hunk 1]
```diff
@@ -2041,6 +2041,22 @@ mod tests {
             .collect()
     }
 
+    #[test]
+    #[cfg(feature = "hardcoded-data")]
+    fn test_reordered_levels_range() {
```
Comment (Manishearth) [inline src/lib.rs:2046]: issue: link to the issue in a comment?

**Review by Manishearth — APPROVED** [review]
Almost there, thanks for the work!!

**Review by Manishearth — APPROVED** [review]
